force-app/main/default/objects/Day_in_the_office__c/Day_in_the_office__c.object-meta.xml
<CustomObject>
    <label>Day In The Office</label>
    <nameField>
        <displayFormat>ATT-{0000}</displayFormat>
        <label>Day in the office Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Days In The Office</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Day_in_the_office__c/fields/Attendance_Date__c.field-meta.xml
<CustomField>
    <fullName>Attendance_Date__c</fullName>
    <label>Attendance Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Day_in_the_office__c/fields/unique_identifier__c.field-meta.xml
<CustomField>
    <fullName>unique_identifier__c</fullName>
    <externalId>true</externalId>
    <label>Unique Identifier</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Day_in_the_office__c/fields/Visitor__c.field-meta.xml
<CustomField>
    <fullName>Visitor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Visitor</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Days In The Office</relationshipLabel>
    <relationshipName>Days_In_The_Office</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Day_in_the_office__c/recordTypes/Visitor_Attendance.recordType-meta.xml
<RecordType>
    <fullName>Visitor_Attendance</fullName>
    <active>true</active>
    <label>Visitor Attendance</label>
</RecordType>

force-app/main/default/classes/VisitorAttendanceInput_Controller.cls
public without sharing class  VisitorAttendanceInput_Controller {
    
    Public Static Final String VisitorRT =  'Visitor_Attendance';
    Public Static Final String vaneigensAccount = 'Vaneigens';
    public static Final Id RT_Visitor = Schema.SObjectType.Day_in_the_office__c.getRecordTypeInfosByDeveloperName().get(VisitorRT).getRecordTypeId();
    
    @AuraEnabled(Cacheable=false)
    public  static void saveAttendance(String email, String firstName, String lastName, Date attendanceDate){
        
        Contact visitor = new Contact(firstName = firstName, LastName = lastName, Email = email);
        //Check Contact existance
        List<Contact> c = [Select id,FirstName,Salutation, LastName, Email from Contact where email = :visitor.email];
        if(c.size()==0){
            Account acc = [Select id From Account where Name = : vaneigensAccount];
            visitor.accountId = acc.Id;
            insert visitor;
        }
        else {
            visitor.Id = c[0].Id;
            update visitor;
        }
        
        Day_In_The_Office__c attendance = new Day_In_The_Office__c(RecordTypeId=RT_Visitor, Visitor__c = visitor.Id,
        Attendance_Date__c = attendanceDate);
        
        insert attendance;
        
        
    }
    
    
    @AuraEnabled(Cacheable=true)
    public static void getAttendances(String email){
        List<Day_In_The_Office__c> attendances =  [Select id, Visitor__r.Email, Visitor__r.Name, unique_identifier__c, Attendance_Date__c from Day_In_The_Office__c 
        where Visitor__r.Email = : email
        ORDER BY Attendance_Date__c DESC];
    }    
    
    
    
}