force-app/main/default/objects/Day_in_the_office__c/Day_in_the_office__c.object-meta.xml
<CustomObject>
    <label>Day In The Office</label>
    <nameField>
        <displayFormat>ATT-{0000}</displayFormat>
        <label>Day in the office Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Days In The Office</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Day_in_the_office__c/fields/Attendance_Date__c.field-meta.xml
<CustomField>
    <fullName>Attendance_Date__c</fullName>
    <label>Attendance Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Day_in_the_office__c/fields/Attendee__c.field-meta.xml
<CustomField>
    <fullName>Attendee__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Attendee</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Days_In_The_Office</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Day_in_the_office__c/fields/AttendeeName__c.field-meta.xml
<CustomField>
    <fullName>AttendeeName__c</fullName>
    <formula>If(Attendee__c &lt;&gt; null,Attendee__r.LastName + &apos; &apos; +  Attendee__r.FirstName,&apos;&apos;)
&amp;
If(Visitor__c &lt;&gt; null, Visitor__r.LastName + &apos; &apos; + Visitor__r.FirstName,&apos;&apos;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>AttendeeName</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Day_in_the_office__c/fields/Day_of_the_Week__c.field-meta.xml
<CustomField>
    <fullName>Day_of_the_Week__c</fullName>
    <formula>CASE( Day_In_the_Week__c, 1, &quot;Sunday&quot; , 2, &quot;Monday&quot;,3,&quot;Tuesday&quot;,4,&quot;Wednesday&quot;,5,&quot;Thursday&quot;,6,&quot;Friday&quot;,7,&quot;Saturday&quot;,&quot;&quot;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Day of the Week</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/attendanceDataController.cls
public  without sharing class attendanceDataController {

    Public static final String THIS_WEEK = 'THIS_WEEK';
    Public static final String THIS_MONTH = 'THIS_MONTH'; 

    @AuraEnabled(cacheable=true)
    public static List<Day_In_The_Office__c>  getAttendanceData(String filterValue, Id userId){
        if(filterValue==THIS_WEEK) return attendanceData_THIS_WEEK(userId);
        else if(filterValue==THIS_MONTH) return attendanceData_THIS_MONTH(userId);
        else return null;
    }

    public static List<Day_In_The_Office__c> attendanceData_THIS_WEEK(Id userId) {
System.debug('this week)');
        return [Select id,Attendance_Date__c, Attendee__r.Name, AttendeeName__c, Day_of_the_Week__c 
        FROM Day_In_The_Office__c 
        WHERE Attendee__c = :userId
        AND Attendance_Date__c = THIS_WEEK
        ORDER BY Attendance_Date__c DESC];
    }

    public static List<Day_In_The_Office__c>  attendanceData_THIS_MONTH(Id userId) {
        System.debug('this month : ' + [Select id,Attendance_Date__c, Attendee__r.Name, AttendeeName__c, Day_of_the_Week__c 
        FROM Day_In_The_Office__c 
        WHERE Attendee__c = :userId
        AND Attendance_Date__c = THIS_MONTH
        ORDER BY Attendance_Date__c DESC]);

        return [Select id,Attendance_Date__c, Attendee__r.Name, AttendeeName__c, Day_of_the_Week__c 
        FROM Day_In_The_Office__c 
        WHERE Attendee__c = :userId
        AND Attendance_Date__c = THIS_MONTH
        ORDER BY Attendance_Date__c DESC ];
    }
    @AuraEnabled(Cacheable=true)
    public static List<Day_In_The_Office__c> attendanceDate_TomorrowAttendees(){
        return  [Select id,RecordType.DeveloperName, AttendeeName__c, Day_of_the_Week__c 
        FROM Day_In_The_Office__c 
        Where Attendance_Date__c = TOMORROW];

    }
}